// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgEt95MLLxnL1lE18gfc9k8Y9MLxm2Ouw',
    appId: '1:743453990456:web:aff40891efc181165f90cd',
    messagingSenderId: '743453990456',
    projectId: 'calcrow-prod',
    authDomain: 'calcrow-prod.firebaseapp.com',
    storageBucket: 'calcrow-prod.firebasestorage.app',
    measurementId: 'G-XL02B747JS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4KFkuDkwawx-ytpNg_6tq6C9HlgPey8M',
    appId: '1:743453990456:android:dc6be13c25cc537f5f90cd',
    messagingSenderId: '743453990456',
    projectId: 'calcrow-prod',
    storageBucket: 'calcrow-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKIIU_p3hDpIEOdQx4z83ukT42JJgJnJk',
    appId: '1:743453990456:ios:7f8f2cefaabeeb1e5f90cd',
    messagingSenderId: '743453990456',
    projectId: 'calcrow-prod',
    storageBucket: 'calcrow-prod.firebasestorage.app',
    iosBundleId: 'de.lemarq.calcrow',
  );

}